#pragma once
namespace Engine {
	enum WINMODE { MODE_FULL, MODE_WIN };
	
	enum COMPONENTID {ID_DYNAMIC, ID_STATIC, ID_END};
	
	enum INFO {INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS,INFO_END};
	enum ROTATION {ROT_X,ROT_Y,ROT_Z, ROT_END};

	enum TEXTUREID{TEX_NORMAL, TEX_CUBE, TEX_END};
	enum RENDERID {RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI,RENDER_END};
	
	enum MOUSEKEYSTATE{DIM_LB,DIM_RB,DIM_MB,DIM_END};
	enum MOUSEMOVESTATE{DIMS_X,DIMD_Y,DIMD_Z,DIMS_END};

	enum class OBJ_TYPE{};
	enum class COM_TYPE{TRANSFROM, RENDERER,MESH, CAMERA};
}