#pragma once

#include "IService.h"
#include "ITimeService.h"
#include "IInputService.h"
#include "IAudioService.h"
#include "IGraphicService.h"
#include "ILevelService.h"
#include "IProtoService.h"
#include "IObjectService.h"
#include "IGUIService.h"
#include "IRenderService.h"
#include "ICameraService.h"
#include "IUI_Service.h"
#include "ILightService.h"
#include "IRayService.h"
#include "ITileService.h"
#include "ICollisionService.h"