#pragma once
#include"CBossState.h"
#include "CBossIdle.h"
#include "CBossWait.h"
#include "CBossIntro.h"
#include "CBossGround.h"
#include "CBossMeteor.h"
#include "CBossHoming.h"
#include "CBossSlash.h"
#include "CBossDead.h"
#include "CBossEnHance.h"
#include "CEnhancedBossDead.h"
#include "CEnhancedBossGround.h"
#include "CEnhancedBossHoming.h"
#include "CEnhancedBossIDLE.h"
#include "CEnhancedBossMeteor.h"
#include "CEnhancedBossRush.h"
#include "CEnhancedBossSlash.h"
